package fr.miage.toulouse.ProjetL3.controleur;

import java.net.URL;
import java.util.ResourceBundle;

import fr.miage.toulouse.ProjetL3.Class.metier.Etudiant;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ListeEtudiant_BureauExamController implements Initializable {
	@FXML
	private TableView<Etudiant> tableView_EtudiantInscrits;
	@FXML
	private TableColumn<Etudiant, String> column_numEtudiant1;
	@FXML
	private TableColumn<Etudiant, String> column_nomEtudiant1;
	@FXML
	private TableColumn<Etudiant, String> column_prenomEtudiant1;
	@FXML
	private TableColumn<Etudiant, String> column_parcoursEtudiant1;
	@FXML
	private TableView<Etudiant> tableView_EtudiantInscrits2;
	@FXML
	private TableColumn<Etudiant, String> column_numEtudiant2;
	@FXML
	private TableColumn<Etudiant, String> column_nomEtudiant2;
	@FXML
	private TableColumn<Etudiant, String> column_prenomEtudiant2;
	@FXML
	private TableColumn<Etudiant, String> column_parcoursEtudiant2;
	@FXML
	private Button btn_annuler;

	// Event Listener on Button[#btn_annuler].onMouseClicked
	@FXML
	public void clear(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onMouseClicked
	@FXML
	public void save(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {

	}
}
