package fr.miage.toulouse.ProjetL3.controleur;

import java.net.URL;
import java.util.ResourceBundle;

import fr.miage.toulouse.ProjetL3.Class.metier.Etudiant;
import fr.miage.toulouse.ProjetL3.Class.metier.UE;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ListeEtudiant_BureauExamController implements Initializable {
	@FXML
	private TableView<Etudiant> tableView_EtudiantInscrits;
	@FXML
	private TableColumn<Etudiant, String> column_numEtudiantInscrits;
	@FXML
	private TableColumn<Etudiant, String> column_nomEtudiantInscrits;
	@FXML
	private TableColumn<Etudiant, String> column_prenomEtudiantInscrits;
	@FXML
	private TableColumn<Etudiant, String> column_parcoursEtudiantInscrits;
	@FXML
	private TableView<Etudiant> tableView_EtudiantInscritsSelection;
	@FXML
	private TableColumn<Etudiant, String> column_numEtudiantSelection;
	@FXML
	private TableColumn<Etudiant, String> column_nomEtudiantSelection;
	@FXML
	private TableColumn<Etudiant, String> column_prenomEtudiantSelection;
	@FXML
	private TableColumn<Etudiant, String> column_parcoursEtudiantSelection;
	@FXML
	private Button btn_annuler;
	@FXML
	private Label label_UE;

	// Observable contenant la liste des différents étudiants inscrits aux UE
	private ObservableList<Etudiant> listEtudiantInscrit = FXCollections.observableArrayList();
	// Observable contenant la liste des différents étudiants qui auront l'UE
	private ObservableList<Etudiant> listEtudiantSelection = FXCollections.observableArrayList();

	// On récupère ici l'ue sélectionné précédemment
	public static UE ueClic;

	@FXML
	public void clear(MouseEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void save(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		label_UE.setText(label_UE.getText() + " " + ueClic.getCodeIdentification());
	}
}
